### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by sarajcev** [sarajcev/PSS-ML#5]

**Comment by sarajcev** [comment]
@akunac Nakon eliminacije parametara generatora (Id, Iq), ulazni podaci sada sadrže 362 umjesto 276 featurea. To je više nego smo imali prije. Mogli bi napraviti još jednu varijantu baze ulaznih podataka bez svih kuteva napona?

**Comment by akunac** [comment]
Moze odradim to za nekih sat vremena. @sarajcev

**Comment by sarajcev** [comment]
@akunac Pregledom novog seta ulaznih podataka i dalje su prisutne struje Id i Iq svih generatora?! Rekli smo eliminirati iz seta sve veličine koje nisu direktno mjerljive. Pogledajte još jednom source code kojim generirate dataset.
